language: node_js
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive