language: node_js
node_js:
  - "12.18.1"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  - firebase deploy --token $FIREBASE_TOKEN --project butterfly-plugin --non-interactive